### ISSUE TITLE
The documentation link in (Readme.md) SAML Jackson section redirects to "Page not found"

### ISSUE THREAD

**Issue by amruth-acharya** [boxyhq/.github#1]
Greetings!

I was going through the repo and clicked documentation link in SAML Jackson in Readme.md, it directs to 
(https://boxyhq.com/docs/jackson/) which gives page not found . I think this might be the  [correct link]( https://boxyhq.com/docs/jackson/overview). 

If it's okay with you , you can assign this to me and I'll work on it.

**Comment by deepakprabhakara** [comment]
Thanks @amruth-acharya, please go ahead.
